/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ListPlansResponsePlansInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPlansResponsePlansInner{}

// ListPlansResponsePlansInner struct for ListPlansResponsePlansInner
type ListPlansResponsePlansInner struct {
	// The name of the plan
	Name string `json:"name"`
	Status PlanStatus `json:"status"`
	BillingData PlanBillingData `json:"billingData"`
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _ListPlansResponsePlansInner ListPlansResponsePlansInner

// NewListPlansResponsePlansInner instantiates a new ListPlansResponsePlansInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPlansResponsePlansInner(name string, status PlanStatus, billingData PlanBillingData, id string, createdAt time.Time, updatedAt time.Time) *ListPlansResponsePlansInner {
	this := ListPlansResponsePlansInner{}
	this.Name = name
	this.Status = status
	this.BillingData = billingData
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewListPlansResponsePlansInnerWithDefaults instantiates a new ListPlansResponsePlansInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPlansResponsePlansInnerWithDefaults() *ListPlansResponsePlansInner {
	this := ListPlansResponsePlansInner{}
	return &this
}

// GetName returns the Name field value
func (o *ListPlansResponsePlansInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListPlansResponsePlansInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListPlansResponsePlansInner) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *ListPlansResponsePlansInner) GetStatus() PlanStatus {
	if o == nil {
		var ret PlanStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ListPlansResponsePlansInner) GetStatusOk() (*PlanStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ListPlansResponsePlansInner) SetStatus(v PlanStatus) {
	o.Status = v
}

// GetBillingData returns the BillingData field value
func (o *ListPlansResponsePlansInner) GetBillingData() PlanBillingData {
	if o == nil {
		var ret PlanBillingData
		return ret
	}

	return o.BillingData
}

// GetBillingDataOk returns a tuple with the BillingData field value
// and a boolean to check if the value has been set.
func (o *ListPlansResponsePlansInner) GetBillingDataOk() (*PlanBillingData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingData, true
}

// SetBillingData sets field value
func (o *ListPlansResponsePlansInner) SetBillingData(v PlanBillingData) {
	o.BillingData = v
}

// GetId returns the Id field value
func (o *ListPlansResponsePlansInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListPlansResponsePlansInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListPlansResponsePlansInner) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListPlansResponsePlansInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListPlansResponsePlansInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListPlansResponsePlansInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ListPlansResponsePlansInner) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ListPlansResponsePlansInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ListPlansResponsePlansInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ListPlansResponsePlansInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPlansResponsePlansInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["billingData"] = o.BillingData
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ListPlansResponsePlansInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"status",
		"billingData",
		"id",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListPlansResponsePlansInner := _ListPlansResponsePlansInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListPlansResponsePlansInner)

	if err != nil {
		return err
	}

	*o = ListPlansResponsePlansInner(varListPlansResponsePlansInner)

	return err
}

type NullableListPlansResponsePlansInner struct {
	value *ListPlansResponsePlansInner
	isSet bool
}

func (v NullableListPlansResponsePlansInner) Get() *ListPlansResponsePlansInner {
	return v.value
}

func (v *NullableListPlansResponsePlansInner) Set(val *ListPlansResponsePlansInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListPlansResponsePlansInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListPlansResponsePlansInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPlansResponsePlansInner(val *ListPlansResponsePlansInner) *NullableListPlansResponsePlansInner {
	return &NullableListPlansResponsePlansInner{value: val, isSet: true}
}

func (v NullableListPlansResponsePlansInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPlansResponsePlansInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


