/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetEventByRefIdResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEventByRefIdResponse{}

// GetEventByRefIdResponse struct for GetEventByRefIdResponse
type GetEventByRefIdResponse struct {
	Event GetEventByRefIdResponseEvent `json:"event"`
	AdditionalProperties map[string]interface{}
}

type _GetEventByRefIdResponse GetEventByRefIdResponse

// NewGetEventByRefIdResponse instantiates a new GetEventByRefIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEventByRefIdResponse(event GetEventByRefIdResponseEvent) *GetEventByRefIdResponse {
	this := GetEventByRefIdResponse{}
	this.Event = event
	return &this
}

// NewGetEventByRefIdResponseWithDefaults instantiates a new GetEventByRefIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEventByRefIdResponseWithDefaults() *GetEventByRefIdResponse {
	this := GetEventByRefIdResponse{}
	return &this
}

// GetEvent returns the Event field value
func (o *GetEventByRefIdResponse) GetEvent() GetEventByRefIdResponseEvent {
	if o == nil {
		var ret GetEventByRefIdResponseEvent
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *GetEventByRefIdResponse) GetEventOk() (*GetEventByRefIdResponseEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *GetEventByRefIdResponse) SetEvent(v GetEventByRefIdResponseEvent) {
	o.Event = v
}

func (o GetEventByRefIdResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEventByRefIdResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetEventByRefIdResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEventByRefIdResponse := _GetEventByRefIdResponse{}

	err = json.Unmarshal(data, &varGetEventByRefIdResponse)

	if err != nil {
		return err
	}

	*o = GetEventByRefIdResponse(varGetEventByRefIdResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetEventByRefIdResponse struct {
	value *GetEventByRefIdResponse
	isSet bool
}

func (v NullableGetEventByRefIdResponse) Get() *GetEventByRefIdResponse {
	return v.value
}

func (v *NullableGetEventByRefIdResponse) Set(val *GetEventByRefIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEventByRefIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEventByRefIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEventByRefIdResponse(val *GetEventByRefIdResponse) *NullableGetEventByRefIdResponse {
	return &NullableGetEventByRefIdResponse{value: val, isSet: true}
}

func (v NullableGetEventByRefIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEventByRefIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


