/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DeleteEventResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteEventResponse{}

// DeleteEventResponse struct for DeleteEventResponse
type DeleteEventResponse struct {
	Event DeleteEventResponseEvent `json:"event"`
	AdditionalProperties map[string]interface{}
}

type _DeleteEventResponse DeleteEventResponse

// NewDeleteEventResponse instantiates a new DeleteEventResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteEventResponse(event DeleteEventResponseEvent) *DeleteEventResponse {
	this := DeleteEventResponse{}
	this.Event = event
	return &this
}

// NewDeleteEventResponseWithDefaults instantiates a new DeleteEventResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteEventResponseWithDefaults() *DeleteEventResponse {
	this := DeleteEventResponse{}
	return &this
}

// GetEvent returns the Event field value
func (o *DeleteEventResponse) GetEvent() DeleteEventResponseEvent {
	if o == nil {
		var ret DeleteEventResponseEvent
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *DeleteEventResponse) GetEventOk() (*DeleteEventResponseEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *DeleteEventResponse) SetEvent(v DeleteEventResponseEvent) {
	o.Event = v
}

func (o DeleteEventResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteEventResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeleteEventResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteEventResponse := _DeleteEventResponse{}

	err = json.Unmarshal(data, &varDeleteEventResponse)

	if err != nil {
		return err
	}

	*o = DeleteEventResponse(varDeleteEventResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteEventResponse struct {
	value *DeleteEventResponse
	isSet bool
}

func (v NullableDeleteEventResponse) Get() *DeleteEventResponse {
	return v.value
}

func (v *NullableDeleteEventResponse) Set(val *DeleteEventResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteEventResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteEventResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteEventResponse(val *DeleteEventResponse) *NullableDeleteEventResponse {
	return &NullableDeleteEventResponse{value: val, isSet: true}
}

func (v NullableDeleteEventResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteEventResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


