/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateCustomerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCustomerResponse{}

// CreateCustomerResponse struct for CreateCustomerResponse
type CreateCustomerResponse struct {
	Customer CreateCustomerResponseCustomer `json:"customer"`
	AdditionalProperties map[string]interface{}
}

type _CreateCustomerResponse CreateCustomerResponse

// NewCreateCustomerResponse instantiates a new CreateCustomerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCustomerResponse(customer CreateCustomerResponseCustomer) *CreateCustomerResponse {
	this := CreateCustomerResponse{}
	this.Customer = customer
	return &this
}

// NewCreateCustomerResponseWithDefaults instantiates a new CreateCustomerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCustomerResponseWithDefaults() *CreateCustomerResponse {
	this := CreateCustomerResponse{}
	return &this
}

// GetCustomer returns the Customer field value
func (o *CreateCustomerResponse) GetCustomer() CreateCustomerResponseCustomer {
	if o == nil {
		var ret CreateCustomerResponseCustomer
		return ret
	}

	return o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value
// and a boolean to check if the value has been set.
func (o *CreateCustomerResponse) GetCustomerOk() (*CreateCustomerResponseCustomer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Customer, true
}

// SetCustomer sets field value
func (o *CreateCustomerResponse) SetCustomer(v CreateCustomerResponseCustomer) {
	o.Customer = v
}

func (o CreateCustomerResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCustomerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customer"] = o.Customer

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateCustomerResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCustomerResponse := _CreateCustomerResponse{}

	err = json.Unmarshal(data, &varCreateCustomerResponse)

	if err != nil {
		return err
	}

	*o = CreateCustomerResponse(varCreateCustomerResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customer")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateCustomerResponse struct {
	value *CreateCustomerResponse
	isSet bool
}

func (v NullableCreateCustomerResponse) Get() *CreateCustomerResponse {
	return v.value
}

func (v *NullableCreateCustomerResponse) Set(val *CreateCustomerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCustomerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCustomerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCustomerResponse(val *CreateCustomerResponse) *NullableCreateCustomerResponse {
	return &NullableCreateCustomerResponse{value: val, isSet: true}
}

func (v NullableCreateCustomerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCustomerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


