/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SendEventsResponseInvalidEventsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendEventsResponseInvalidEventsInner{}

// SendEventsResponseInvalidEventsInner struct for SendEventsResponseInvalidEventsInner
type SendEventsResponseInvalidEventsInner struct {
	Event EventsDryRunRequestEventsInner `json:"event"`
	// The error message indicating the reason the event failed validation.
	Error string `json:"error"`
	AdditionalProperties map[string]interface{}
}

type _SendEventsResponseInvalidEventsInner SendEventsResponseInvalidEventsInner

// NewSendEventsResponseInvalidEventsInner instantiates a new SendEventsResponseInvalidEventsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendEventsResponseInvalidEventsInner(event EventsDryRunRequestEventsInner, error_ string) *SendEventsResponseInvalidEventsInner {
	this := SendEventsResponseInvalidEventsInner{}
	this.Event = event
	this.Error = error_
	return &this
}

// NewSendEventsResponseInvalidEventsInnerWithDefaults instantiates a new SendEventsResponseInvalidEventsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendEventsResponseInvalidEventsInnerWithDefaults() *SendEventsResponseInvalidEventsInner {
	this := SendEventsResponseInvalidEventsInner{}
	return &this
}

// GetEvent returns the Event field value
func (o *SendEventsResponseInvalidEventsInner) GetEvent() EventsDryRunRequestEventsInner {
	if o == nil {
		var ret EventsDryRunRequestEventsInner
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *SendEventsResponseInvalidEventsInner) GetEventOk() (*EventsDryRunRequestEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *SendEventsResponseInvalidEventsInner) SetEvent(v EventsDryRunRequestEventsInner) {
	o.Event = v
}

// GetError returns the Error field value
func (o *SendEventsResponseInvalidEventsInner) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *SendEventsResponseInvalidEventsInner) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *SendEventsResponseInvalidEventsInner) SetError(v string) {
	o.Error = v
}

func (o SendEventsResponseInvalidEventsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendEventsResponseInvalidEventsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["error"] = o.Error

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SendEventsResponseInvalidEventsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendEventsResponseInvalidEventsInner := _SendEventsResponseInvalidEventsInner{}

	err = json.Unmarshal(data, &varSendEventsResponseInvalidEventsInner)

	if err != nil {
		return err
	}

	*o = SendEventsResponseInvalidEventsInner(varSendEventsResponseInvalidEventsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		delete(additionalProperties, "error")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSendEventsResponseInvalidEventsInner struct {
	value *SendEventsResponseInvalidEventsInner
	isSet bool
}

func (v NullableSendEventsResponseInvalidEventsInner) Get() *SendEventsResponseInvalidEventsInner {
	return v.value
}

func (v *NullableSendEventsResponseInvalidEventsInner) Set(val *SendEventsResponseInvalidEventsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSendEventsResponseInvalidEventsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSendEventsResponseInvalidEventsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendEventsResponseInvalidEventsInner(val *SendEventsResponseInvalidEventsInner) *NullableSendEventsResponseInvalidEventsInner {
	return &NullableSendEventsResponseInvalidEventsInner{value: val, isSet: true}
}

func (v NullableSendEventsResponseInvalidEventsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendEventsResponseInvalidEventsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


