/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetInvoiceResponseInvoiceLineItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInvoiceResponseInvoiceLineItemsInner{}

// GetInvoiceResponseInvoiceLineItemsInner struct for GetInvoiceResponseInvoiceLineItemsInner
type GetInvoiceResponseInvoiceLineItemsInner struct {
	// The id of the invoice that the line item is a part of
	InvoiceId string `json:"invoiceId" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// The price of the line item
	Price float32 `json:"price"`
}

type _GetInvoiceResponseInvoiceLineItemsInner GetInvoiceResponseInvoiceLineItemsInner

// NewGetInvoiceResponseInvoiceLineItemsInner instantiates a new GetInvoiceResponseInvoiceLineItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInvoiceResponseInvoiceLineItemsInner(invoiceId string, price float32) *GetInvoiceResponseInvoiceLineItemsInner {
	this := GetInvoiceResponseInvoiceLineItemsInner{}
	this.InvoiceId = invoiceId
	this.Price = price
	return &this
}

// NewGetInvoiceResponseInvoiceLineItemsInnerWithDefaults instantiates a new GetInvoiceResponseInvoiceLineItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInvoiceResponseInvoiceLineItemsInnerWithDefaults() *GetInvoiceResponseInvoiceLineItemsInner {
	this := GetInvoiceResponseInvoiceLineItemsInner{}
	return &this
}

// GetInvoiceId returns the InvoiceId field value
func (o *GetInvoiceResponseInvoiceLineItemsInner) GetInvoiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value
// and a boolean to check if the value has been set.
func (o *GetInvoiceResponseInvoiceLineItemsInner) GetInvoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceId, true
}

// SetInvoiceId sets field value
func (o *GetInvoiceResponseInvoiceLineItemsInner) SetInvoiceId(v string) {
	o.InvoiceId = v
}

// GetPrice returns the Price field value
func (o *GetInvoiceResponseInvoiceLineItemsInner) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *GetInvoiceResponseInvoiceLineItemsInner) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *GetInvoiceResponseInvoiceLineItemsInner) SetPrice(v float32) {
	o.Price = v
}

func (o GetInvoiceResponseInvoiceLineItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInvoiceResponseInvoiceLineItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invoiceId"] = o.InvoiceId
	toSerialize["price"] = o.Price
	return toSerialize, nil
}

func (o *GetInvoiceResponseInvoiceLineItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invoiceId",
		"price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetInvoiceResponseInvoiceLineItemsInner := _GetInvoiceResponseInvoiceLineItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetInvoiceResponseInvoiceLineItemsInner)

	if err != nil {
		return err
	}

	*o = GetInvoiceResponseInvoiceLineItemsInner(varGetInvoiceResponseInvoiceLineItemsInner)

	return err
}

type NullableGetInvoiceResponseInvoiceLineItemsInner struct {
	value *GetInvoiceResponseInvoiceLineItemsInner
	isSet bool
}

func (v NullableGetInvoiceResponseInvoiceLineItemsInner) Get() *GetInvoiceResponseInvoiceLineItemsInner {
	return v.value
}

func (v *NullableGetInvoiceResponseInvoiceLineItemsInner) Set(val *GetInvoiceResponseInvoiceLineItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInvoiceResponseInvoiceLineItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInvoiceResponseInvoiceLineItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInvoiceResponseInvoiceLineItemsInner(val *GetInvoiceResponseInvoiceLineItemsInner) *NullableGetInvoiceResponseInvoiceLineItemsInner {
	return &NullableGetInvoiceResponseInvoiceLineItemsInner{value: val, isSet: true}
}

func (v NullableGetInvoiceResponseInvoiceLineItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInvoiceResponseInvoiceLineItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


