/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the Meter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Meter{}

// Meter struct for Meter
type Meter struct {
	// The name of the meter
	Name string `json:"name"`
	// The name of the event that the meter is tracking.
	EventName string `json:"eventName"`
	AggregationMethod AggregationMethod `json:"aggregationMethod"`
	Filter *Filter `json:"filter,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Meter Meter

// NewMeter instantiates a new Meter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeter(name string, eventName string, aggregationMethod AggregationMethod) *Meter {
	this := Meter{}
	this.Name = name
	this.EventName = eventName
	this.AggregationMethod = aggregationMethod
	return &this
}

// NewMeterWithDefaults instantiates a new Meter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeterWithDefaults() *Meter {
	this := Meter{}
	return &this
}

// GetName returns the Name field value
func (o *Meter) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Meter) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Meter) SetName(v string) {
	o.Name = v
}

// GetEventName returns the EventName field value
func (o *Meter) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *Meter) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *Meter) SetEventName(v string) {
	o.EventName = v
}

// GetAggregationMethod returns the AggregationMethod field value
func (o *Meter) GetAggregationMethod() AggregationMethod {
	if o == nil {
		var ret AggregationMethod
		return ret
	}

	return o.AggregationMethod
}

// GetAggregationMethodOk returns a tuple with the AggregationMethod field value
// and a boolean to check if the value has been set.
func (o *Meter) GetAggregationMethodOk() (*AggregationMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AggregationMethod, true
}

// SetAggregationMethod sets field value
func (o *Meter) SetAggregationMethod(v AggregationMethod) {
	o.AggregationMethod = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *Meter) GetFilter() Filter {
	if o == nil || IsNil(o.Filter) {
		var ret Filter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meter) GetFilterOk() (*Filter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *Meter) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given Filter and assigns it to the Filter field.
func (o *Meter) SetFilter(v Filter) {
	o.Filter = &v
}

func (o Meter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Meter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["eventName"] = o.EventName
	toSerialize["aggregationMethod"] = o.AggregationMethod
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Meter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"eventName",
		"aggregationMethod",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeter := _Meter{}

	err = json.Unmarshal(data, &varMeter)

	if err != nil {
		return err
	}

	*o = Meter(varMeter)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "eventName")
		delete(additionalProperties, "aggregationMethod")
		delete(additionalProperties, "filter")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMeter struct {
	value *Meter
	isSet bool
}

func (v NullableMeter) Get() *Meter {
	return v.value
}

func (v *NullableMeter) Set(val *Meter) {
	v.value = val
	v.isSet = true
}

func (v NullableMeter) IsSet() bool {
	return v.isSet
}

func (v *NullableMeter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeter(val *Meter) *NullableMeter {
	return &NullableMeter{value: val, isSet: true}
}

func (v NullableMeter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


