/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ListInvoicesResponseInvoicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListInvoicesResponseInvoicesInner{}

// ListInvoicesResponseInvoicesInner struct for ListInvoicesResponseInvoicesInner
type ListInvoicesResponseInvoicesInner struct {
	// The id of the customer that the invoice is associated with
	CustomerId string `json:"customerId" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// The id of the contract that the invoice is associated with
	ContractId *string `json:"contractId,omitempty" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// The name of the invoice, usually a description of the billing period
	Name string `json:"name"`
	BillingCycle Period `json:"billingCycle"`
	LineItems []GetInvoiceResponseInvoiceLineItemsInner `json:"lineItems"`
	// The total amount of the invoice
	Amount float32 `json:"amount"`
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _ListInvoicesResponseInvoicesInner ListInvoicesResponseInvoicesInner

// NewListInvoicesResponseInvoicesInner instantiates a new ListInvoicesResponseInvoicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListInvoicesResponseInvoicesInner(customerId string, name string, billingCycle Period, lineItems []GetInvoiceResponseInvoiceLineItemsInner, amount float32, id string, createdAt time.Time, updatedAt time.Time) *ListInvoicesResponseInvoicesInner {
	this := ListInvoicesResponseInvoicesInner{}
	this.CustomerId = customerId
	this.Name = name
	this.BillingCycle = billingCycle
	this.LineItems = lineItems
	this.Amount = amount
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewListInvoicesResponseInvoicesInnerWithDefaults instantiates a new ListInvoicesResponseInvoicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListInvoicesResponseInvoicesInnerWithDefaults() *ListInvoicesResponseInvoicesInner {
	this := ListInvoicesResponseInvoicesInner{}
	return &this
}

// GetCustomerId returns the CustomerId field value
func (o *ListInvoicesResponseInvoicesInner) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponseInvoicesInner) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *ListInvoicesResponseInvoicesInner) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetContractId returns the ContractId field value if set, zero value otherwise.
func (o *ListInvoicesResponseInvoicesInner) GetContractId() string {
	if o == nil || IsNil(o.ContractId) {
		var ret string
		return ret
	}
	return *o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponseInvoicesInner) GetContractIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContractId) {
		return nil, false
	}
	return o.ContractId, true
}

// HasContractId returns a boolean if a field has been set.
func (o *ListInvoicesResponseInvoicesInner) HasContractId() bool {
	if o != nil && !IsNil(o.ContractId) {
		return true
	}

	return false
}

// SetContractId gets a reference to the given string and assigns it to the ContractId field.
func (o *ListInvoicesResponseInvoicesInner) SetContractId(v string) {
	o.ContractId = &v
}

// GetName returns the Name field value
func (o *ListInvoicesResponseInvoicesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponseInvoicesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListInvoicesResponseInvoicesInner) SetName(v string) {
	o.Name = v
}

// GetBillingCycle returns the BillingCycle field value
func (o *ListInvoicesResponseInvoicesInner) GetBillingCycle() Period {
	if o == nil {
		var ret Period
		return ret
	}

	return o.BillingCycle
}

// GetBillingCycleOk returns a tuple with the BillingCycle field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponseInvoicesInner) GetBillingCycleOk() (*Period, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingCycle, true
}

// SetBillingCycle sets field value
func (o *ListInvoicesResponseInvoicesInner) SetBillingCycle(v Period) {
	o.BillingCycle = v
}

// GetLineItems returns the LineItems field value
func (o *ListInvoicesResponseInvoicesInner) GetLineItems() []GetInvoiceResponseInvoiceLineItemsInner {
	if o == nil {
		var ret []GetInvoiceResponseInvoiceLineItemsInner
		return ret
	}

	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponseInvoicesInner) GetLineItemsOk() ([]GetInvoiceResponseInvoiceLineItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.LineItems, true
}

// SetLineItems sets field value
func (o *ListInvoicesResponseInvoicesInner) SetLineItems(v []GetInvoiceResponseInvoiceLineItemsInner) {
	o.LineItems = v
}

// GetAmount returns the Amount field value
func (o *ListInvoicesResponseInvoicesInner) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponseInvoicesInner) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ListInvoicesResponseInvoicesInner) SetAmount(v float32) {
	o.Amount = v
}

// GetId returns the Id field value
func (o *ListInvoicesResponseInvoicesInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponseInvoicesInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListInvoicesResponseInvoicesInner) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListInvoicesResponseInvoicesInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponseInvoicesInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListInvoicesResponseInvoicesInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ListInvoicesResponseInvoicesInner) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponseInvoicesInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ListInvoicesResponseInvoicesInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ListInvoicesResponseInvoicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListInvoicesResponseInvoicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customerId"] = o.CustomerId
	if !IsNil(o.ContractId) {
		toSerialize["contractId"] = o.ContractId
	}
	toSerialize["name"] = o.Name
	toSerialize["billingCycle"] = o.BillingCycle
	toSerialize["lineItems"] = o.LineItems
	toSerialize["amount"] = o.Amount
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListInvoicesResponseInvoicesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customerId",
		"name",
		"billingCycle",
		"lineItems",
		"amount",
		"id",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListInvoicesResponseInvoicesInner := _ListInvoicesResponseInvoicesInner{}

	err = json.Unmarshal(data, &varListInvoicesResponseInvoicesInner)

	if err != nil {
		return err
	}

	*o = ListInvoicesResponseInvoicesInner(varListInvoicesResponseInvoicesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customerId")
		delete(additionalProperties, "contractId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "billingCycle")
		delete(additionalProperties, "lineItems")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "id")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListInvoicesResponseInvoicesInner struct {
	value *ListInvoicesResponseInvoicesInner
	isSet bool
}

func (v NullableListInvoicesResponseInvoicesInner) Get() *ListInvoicesResponseInvoicesInner {
	return v.value
}

func (v *NullableListInvoicesResponseInvoicesInner) Set(val *ListInvoicesResponseInvoicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListInvoicesResponseInvoicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListInvoicesResponseInvoicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListInvoicesResponseInvoicesInner(val *ListInvoicesResponseInvoicesInner) *NullableListInvoicesResponseInvoicesInner {
	return &NullableListInvoicesResponseInvoicesInner{value: val, isSet: true}
}

func (v NullableListInvoicesResponseInvoicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListInvoicesResponseInvoicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


