/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NetSuiteSyncInvoicesRequestDataEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetSuiteSyncInvoicesRequestDataEntity{}

// NetSuiteSyncInvoicesRequestDataEntity struct for NetSuiteSyncInvoicesRequestDataEntity
type NetSuiteSyncInvoicesRequestDataEntity struct {
	Id string `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _NetSuiteSyncInvoicesRequestDataEntity NetSuiteSyncInvoicesRequestDataEntity

// NewNetSuiteSyncInvoicesRequestDataEntity instantiates a new NetSuiteSyncInvoicesRequestDataEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetSuiteSyncInvoicesRequestDataEntity(id string) *NetSuiteSyncInvoicesRequestDataEntity {
	this := NetSuiteSyncInvoicesRequestDataEntity{}
	this.Id = id
	return &this
}

// NewNetSuiteSyncInvoicesRequestDataEntityWithDefaults instantiates a new NetSuiteSyncInvoicesRequestDataEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetSuiteSyncInvoicesRequestDataEntityWithDefaults() *NetSuiteSyncInvoicesRequestDataEntity {
	this := NetSuiteSyncInvoicesRequestDataEntity{}
	return &this
}

// GetId returns the Id field value
func (o *NetSuiteSyncInvoicesRequestDataEntity) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NetSuiteSyncInvoicesRequestDataEntity) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetSuiteSyncInvoicesRequestDataEntity) SetId(v string) {
	o.Id = v
}

func (o NetSuiteSyncInvoicesRequestDataEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetSuiteSyncInvoicesRequestDataEntity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NetSuiteSyncInvoicesRequestDataEntity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetSuiteSyncInvoicesRequestDataEntity := _NetSuiteSyncInvoicesRequestDataEntity{}

	err = json.Unmarshal(data, &varNetSuiteSyncInvoicesRequestDataEntity)

	if err != nil {
		return err
	}

	*o = NetSuiteSyncInvoicesRequestDataEntity(varNetSuiteSyncInvoicesRequestDataEntity)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNetSuiteSyncInvoicesRequestDataEntity struct {
	value *NetSuiteSyncInvoicesRequestDataEntity
	isSet bool
}

func (v NullableNetSuiteSyncInvoicesRequestDataEntity) Get() *NetSuiteSyncInvoicesRequestDataEntity {
	return v.value
}

func (v *NullableNetSuiteSyncInvoicesRequestDataEntity) Set(val *NetSuiteSyncInvoicesRequestDataEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableNetSuiteSyncInvoicesRequestDataEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableNetSuiteSyncInvoicesRequestDataEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetSuiteSyncInvoicesRequestDataEntity(val *NetSuiteSyncInvoicesRequestDataEntity) *NullableNetSuiteSyncInvoicesRequestDataEntity {
	return &NullableNetSuiteSyncInvoicesRequestDataEntity{value: val, isSet: true}
}

func (v NullableNetSuiteSyncInvoicesRequestDataEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetSuiteSyncInvoicesRequestDataEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


