/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the EventsDryRunResponseObjectEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventsDryRunResponseObjectEvent{}

// EventsDryRunResponseObjectEvent struct for EventsDryRunResponseObjectEvent
type EventsDryRunResponseObjectEvent struct {
	Timestamp time.Time `json:"timestamp"`
	CustomerAlias string `json:"customerAlias"`
	AccountId string `json:"accountId" validate:"regexp=^[0-9a-fA-F]{24}$"`
	Data map[string]interface{} `json:"data,omitempty"`
	Ref string `json:"ref"`
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _EventsDryRunResponseObjectEvent EventsDryRunResponseObjectEvent

// NewEventsDryRunResponseObjectEvent instantiates a new EventsDryRunResponseObjectEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsDryRunResponseObjectEvent(timestamp time.Time, customerAlias string, accountId string, ref string, name string) *EventsDryRunResponseObjectEvent {
	this := EventsDryRunResponseObjectEvent{}
	this.Timestamp = timestamp
	this.CustomerAlias = customerAlias
	this.AccountId = accountId
	this.Ref = ref
	this.Name = name
	return &this
}

// NewEventsDryRunResponseObjectEventWithDefaults instantiates a new EventsDryRunResponseObjectEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsDryRunResponseObjectEventWithDefaults() *EventsDryRunResponseObjectEvent {
	this := EventsDryRunResponseObjectEvent{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *EventsDryRunResponseObjectEvent) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseObjectEvent) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *EventsDryRunResponseObjectEvent) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetCustomerAlias returns the CustomerAlias field value
func (o *EventsDryRunResponseObjectEvent) GetCustomerAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerAlias
}

// GetCustomerAliasOk returns a tuple with the CustomerAlias field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseObjectEvent) GetCustomerAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerAlias, true
}

// SetCustomerAlias sets field value
func (o *EventsDryRunResponseObjectEvent) SetCustomerAlias(v string) {
	o.CustomerAlias = v
}

// GetAccountId returns the AccountId field value
func (o *EventsDryRunResponseObjectEvent) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseObjectEvent) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *EventsDryRunResponseObjectEvent) SetAccountId(v string) {
	o.AccountId = v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EventsDryRunResponseObjectEvent) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventsDryRunResponseObjectEvent) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EventsDryRunResponseObjectEvent) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *EventsDryRunResponseObjectEvent) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetRef returns the Ref field value
func (o *EventsDryRunResponseObjectEvent) GetRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ref
}

// GetRefOk returns a tuple with the Ref field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseObjectEvent) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ref, true
}

// SetRef sets field value
func (o *EventsDryRunResponseObjectEvent) SetRef(v string) {
	o.Ref = v
}

// GetName returns the Name field value
func (o *EventsDryRunResponseObjectEvent) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseObjectEvent) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EventsDryRunResponseObjectEvent) SetName(v string) {
	o.Name = v
}

func (o EventsDryRunResponseObjectEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventsDryRunResponseObjectEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["customerAlias"] = o.CustomerAlias
	toSerialize["accountId"] = o.AccountId
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	toSerialize["ref"] = o.Ref
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventsDryRunResponseObjectEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timestamp",
		"customerAlias",
		"accountId",
		"ref",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventsDryRunResponseObjectEvent := _EventsDryRunResponseObjectEvent{}

	err = json.Unmarshal(data, &varEventsDryRunResponseObjectEvent)

	if err != nil {
		return err
	}

	*o = EventsDryRunResponseObjectEvent(varEventsDryRunResponseObjectEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "customerAlias")
		delete(additionalProperties, "accountId")
		delete(additionalProperties, "data")
		delete(additionalProperties, "ref")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEventsDryRunResponseObjectEvent struct {
	value *EventsDryRunResponseObjectEvent
	isSet bool
}

func (v NullableEventsDryRunResponseObjectEvent) Get() *EventsDryRunResponseObjectEvent {
	return v.value
}

func (v *NullableEventsDryRunResponseObjectEvent) Set(val *EventsDryRunResponseObjectEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsDryRunResponseObjectEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsDryRunResponseObjectEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsDryRunResponseObjectEvent(val *EventsDryRunResponseObjectEvent) *NullableEventsDryRunResponseObjectEvent {
	return &NullableEventsDryRunResponseObjectEvent{value: val, isSet: true}
}

func (v NullableEventsDryRunResponseObjectEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsDryRunResponseObjectEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


