/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ListInvoicesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListInvoicesResponse{}

// ListInvoicesResponse struct for ListInvoicesResponse
type ListInvoicesResponse struct {
	Invoices []GetInvoiceResponseInvoice `json:"invoices"`
	Total float32 `json:"total"`
	HasMore bool `json:"hasMore"`
	NextCursor *string `json:"nextCursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListInvoicesResponse ListInvoicesResponse

// NewListInvoicesResponse instantiates a new ListInvoicesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListInvoicesResponse(invoices []GetInvoiceResponseInvoice, total float32, hasMore bool) *ListInvoicesResponse {
	this := ListInvoicesResponse{}
	this.Invoices = invoices
	this.Total = total
	this.HasMore = hasMore
	return &this
}

// NewListInvoicesResponseWithDefaults instantiates a new ListInvoicesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListInvoicesResponseWithDefaults() *ListInvoicesResponse {
	this := ListInvoicesResponse{}
	return &this
}

// GetInvoices returns the Invoices field value
func (o *ListInvoicesResponse) GetInvoices() []GetInvoiceResponseInvoice {
	if o == nil {
		var ret []GetInvoiceResponseInvoice
		return ret
	}

	return o.Invoices
}

// GetInvoicesOk returns a tuple with the Invoices field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponse) GetInvoicesOk() ([]GetInvoiceResponseInvoice, bool) {
	if o == nil {
		return nil, false
	}
	return o.Invoices, true
}

// SetInvoices sets field value
func (o *ListInvoicesResponse) SetInvoices(v []GetInvoiceResponseInvoice) {
	o.Invoices = v
}

// GetTotal returns the Total field value
func (o *ListInvoicesResponse) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponse) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ListInvoicesResponse) SetTotal(v float32) {
	o.Total = v
}

// GetHasMore returns the HasMore field value
func (o *ListInvoicesResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListInvoicesResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *ListInvoicesResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListInvoicesResponse) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *ListInvoicesResponse) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *ListInvoicesResponse) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o ListInvoicesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListInvoicesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invoices"] = o.Invoices
	toSerialize["total"] = o.Total
	toSerialize["hasMore"] = o.HasMore
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListInvoicesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invoices",
		"total",
		"hasMore",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListInvoicesResponse := _ListInvoicesResponse{}

	err = json.Unmarshal(data, &varListInvoicesResponse)

	if err != nil {
		return err
	}

	*o = ListInvoicesResponse(varListInvoicesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "invoices")
		delete(additionalProperties, "total")
		delete(additionalProperties, "hasMore")
		delete(additionalProperties, "nextCursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListInvoicesResponse struct {
	value *ListInvoicesResponse
	isSet bool
}

func (v NullableListInvoicesResponse) Get() *ListInvoicesResponse {
	return v.value
}

func (v *NullableListInvoicesResponse) Set(val *ListInvoicesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListInvoicesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListInvoicesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListInvoicesResponse(val *ListInvoicesResponse) *NullableListInvoicesResponse {
	return &NullableListInvoicesResponse{value: val, isSet: true}
}

func (v NullableListInvoicesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListInvoicesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


