/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetContractResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetContractResponse{}

// GetContractResponse struct for GetContractResponse
type GetContractResponse struct {
	Contract GetContractResponseContract `json:"contract"`
}

type _GetContractResponse GetContractResponse

// NewGetContractResponse instantiates a new GetContractResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContractResponse(contract GetContractResponseContract) *GetContractResponse {
	this := GetContractResponse{}
	this.Contract = contract
	return &this
}

// NewGetContractResponseWithDefaults instantiates a new GetContractResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContractResponseWithDefaults() *GetContractResponse {
	this := GetContractResponse{}
	return &this
}

// GetContract returns the Contract field value
func (o *GetContractResponse) GetContract() GetContractResponseContract {
	if o == nil {
		var ret GetContractResponseContract
		return ret
	}

	return o.Contract
}

// GetContractOk returns a tuple with the Contract field value
// and a boolean to check if the value has been set.
func (o *GetContractResponse) GetContractOk() (*GetContractResponseContract, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contract, true
}

// SetContract sets field value
func (o *GetContractResponse) SetContract(v GetContractResponseContract) {
	o.Contract = v
}

func (o GetContractResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetContractResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contract"] = o.Contract
	return toSerialize, nil
}

func (o *GetContractResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contract",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetContractResponse := _GetContractResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetContractResponse)

	if err != nil {
		return err
	}

	*o = GetContractResponse(varGetContractResponse)

	return err
}

type NullableGetContractResponse struct {
	value *GetContractResponse
	isSet bool
}

func (v NullableGetContractResponse) Get() *GetContractResponse {
	return v.value
}

func (v *NullableGetContractResponse) Set(val *GetContractResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContractResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContractResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContractResponse(val *GetContractResponse) *NullableGetContractResponse {
	return &NullableGetContractResponse{value: val, isSet: true}
}

func (v NullableGetContractResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContractResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


