/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GetPlanResponsePlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPlanResponsePlan{}

// GetPlanResponsePlan struct for GetPlanResponsePlan
type GetPlanResponsePlan struct {
	// The name of the plan
	Name string `json:"name"`
	Status PlanStatus `json:"status"`
	BillingData PlanBillingData `json:"billingData"`
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	DeletedAt string `json:"deletedAt"`
}

type _GetPlanResponsePlan GetPlanResponsePlan

// NewGetPlanResponsePlan instantiates a new GetPlanResponsePlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPlanResponsePlan(name string, status PlanStatus, billingData PlanBillingData, id string, createdAt time.Time, updatedAt time.Time, deletedAt string) *GetPlanResponsePlan {
	this := GetPlanResponsePlan{}
	this.Name = name
	this.Status = status
	this.BillingData = billingData
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.DeletedAt = deletedAt
	return &this
}

// NewGetPlanResponsePlanWithDefaults instantiates a new GetPlanResponsePlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPlanResponsePlanWithDefaults() *GetPlanResponsePlan {
	this := GetPlanResponsePlan{}
	return &this
}

// GetName returns the Name field value
func (o *GetPlanResponsePlan) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetPlanResponsePlan) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetPlanResponsePlan) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *GetPlanResponsePlan) GetStatus() PlanStatus {
	if o == nil {
		var ret PlanStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetPlanResponsePlan) GetStatusOk() (*PlanStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetPlanResponsePlan) SetStatus(v PlanStatus) {
	o.Status = v
}

// GetBillingData returns the BillingData field value
func (o *GetPlanResponsePlan) GetBillingData() PlanBillingData {
	if o == nil {
		var ret PlanBillingData
		return ret
	}

	return o.BillingData
}

// GetBillingDataOk returns a tuple with the BillingData field value
// and a boolean to check if the value has been set.
func (o *GetPlanResponsePlan) GetBillingDataOk() (*PlanBillingData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingData, true
}

// SetBillingData sets field value
func (o *GetPlanResponsePlan) SetBillingData(v PlanBillingData) {
	o.BillingData = v
}

// GetId returns the Id field value
func (o *GetPlanResponsePlan) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetPlanResponsePlan) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetPlanResponsePlan) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetPlanResponsePlan) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetPlanResponsePlan) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetPlanResponsePlan) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetPlanResponsePlan) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetPlanResponsePlan) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetPlanResponsePlan) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetDeletedAt returns the DeletedAt field value
func (o *GetPlanResponsePlan) GetDeletedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value
// and a boolean to check if the value has been set.
func (o *GetPlanResponsePlan) GetDeletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeletedAt, true
}

// SetDeletedAt sets field value
func (o *GetPlanResponsePlan) SetDeletedAt(v string) {
	o.DeletedAt = v
}

func (o GetPlanResponsePlan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPlanResponsePlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["billingData"] = o.BillingData
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["deletedAt"] = o.DeletedAt
	return toSerialize, nil
}

func (o *GetPlanResponsePlan) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"status",
		"billingData",
		"id",
		"createdAt",
		"updatedAt",
		"deletedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPlanResponsePlan := _GetPlanResponsePlan{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetPlanResponsePlan)

	if err != nil {
		return err
	}

	*o = GetPlanResponsePlan(varGetPlanResponsePlan)

	return err
}

type NullableGetPlanResponsePlan struct {
	value *GetPlanResponsePlan
	isSet bool
}

func (v NullableGetPlanResponsePlan) Get() *GetPlanResponsePlan {
	return v.value
}

func (v *NullableGetPlanResponsePlan) Set(val *GetPlanResponsePlan) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPlanResponsePlan) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPlanResponsePlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPlanResponsePlan(val *GetPlanResponsePlan) *NullableGetPlanResponsePlan {
	return &NullableGetPlanResponsePlan{value: val, isSet: true}
}

func (v NullableGetPlanResponsePlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPlanResponsePlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


