/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventsDryRunResponseInnerMeterWithValuesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventsDryRunResponseInnerMeterWithValuesInner{}

// EventsDryRunResponseInnerMeterWithValuesInner struct for EventsDryRunResponseInnerMeterWithValuesInner
type EventsDryRunResponseInnerMeterWithValuesInner struct {
	// The name of the meter
	Name string `json:"name"`
	// The name of the event that the meter is tracking.
	EventName string `json:"eventName"`
	AggregationMethod GetMeterResponseMeterAggregationMethod `json:"aggregationMethod"`
	Filter *Filter `json:"filter,omitempty"`
	Value float32 `json:"value"`
	InstanceValue interface{} `json:"instanceValue,omitempty"`
}

type _EventsDryRunResponseInnerMeterWithValuesInner EventsDryRunResponseInnerMeterWithValuesInner

// NewEventsDryRunResponseInnerMeterWithValuesInner instantiates a new EventsDryRunResponseInnerMeterWithValuesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsDryRunResponseInnerMeterWithValuesInner(name string, eventName string, aggregationMethod GetMeterResponseMeterAggregationMethod, value float32) *EventsDryRunResponseInnerMeterWithValuesInner {
	this := EventsDryRunResponseInnerMeterWithValuesInner{}
	this.Name = name
	this.EventName = eventName
	this.AggregationMethod = aggregationMethod
	this.Value = value
	return &this
}

// NewEventsDryRunResponseInnerMeterWithValuesInnerWithDefaults instantiates a new EventsDryRunResponseInnerMeterWithValuesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsDryRunResponseInnerMeterWithValuesInnerWithDefaults() *EventsDryRunResponseInnerMeterWithValuesInner {
	this := EventsDryRunResponseInnerMeterWithValuesInner{}
	return &this
}

// GetName returns the Name field value
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EventsDryRunResponseInnerMeterWithValuesInner) SetName(v string) {
	o.Name = v
}

// GetEventName returns the EventName field value
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *EventsDryRunResponseInnerMeterWithValuesInner) SetEventName(v string) {
	o.EventName = v
}

// GetAggregationMethod returns the AggregationMethod field value
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetAggregationMethod() GetMeterResponseMeterAggregationMethod {
	if o == nil {
		var ret GetMeterResponseMeterAggregationMethod
		return ret
	}

	return o.AggregationMethod
}

// GetAggregationMethodOk returns a tuple with the AggregationMethod field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetAggregationMethodOk() (*GetMeterResponseMeterAggregationMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AggregationMethod, true
}

// SetAggregationMethod sets field value
func (o *EventsDryRunResponseInnerMeterWithValuesInner) SetAggregationMethod(v GetMeterResponseMeterAggregationMethod) {
	o.AggregationMethod = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetFilter() Filter {
	if o == nil || IsNil(o.Filter) {
		var ret Filter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetFilterOk() (*Filter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given Filter and assigns it to the Filter field.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) SetFilter(v Filter) {
	o.Filter = &v
}

// GetValue returns the Value field value
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *EventsDryRunResponseInnerMeterWithValuesInner) SetValue(v float32) {
	o.Value = v
}

// GetInstanceValue returns the InstanceValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetInstanceValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InstanceValue
}

// GetInstanceValueOk returns a tuple with the InstanceValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventsDryRunResponseInnerMeterWithValuesInner) GetInstanceValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InstanceValue) {
		return nil, false
	}
	return &o.InstanceValue, true
}

// HasInstanceValue returns a boolean if a field has been set.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) HasInstanceValue() bool {
	if o != nil && !IsNil(o.InstanceValue) {
		return true
	}

	return false
}

// SetInstanceValue gets a reference to the given interface{} and assigns it to the InstanceValue field.
func (o *EventsDryRunResponseInnerMeterWithValuesInner) SetInstanceValue(v interface{}) {
	o.InstanceValue = v
}

func (o EventsDryRunResponseInnerMeterWithValuesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventsDryRunResponseInnerMeterWithValuesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["eventName"] = o.EventName
	toSerialize["aggregationMethod"] = o.AggregationMethod
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	toSerialize["value"] = o.Value
	if o.InstanceValue != nil {
		toSerialize["instanceValue"] = o.InstanceValue
	}
	return toSerialize, nil
}

func (o *EventsDryRunResponseInnerMeterWithValuesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"eventName",
		"aggregationMethod",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventsDryRunResponseInnerMeterWithValuesInner := _EventsDryRunResponseInnerMeterWithValuesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventsDryRunResponseInnerMeterWithValuesInner)

	if err != nil {
		return err
	}

	*o = EventsDryRunResponseInnerMeterWithValuesInner(varEventsDryRunResponseInnerMeterWithValuesInner)

	return err
}

type NullableEventsDryRunResponseInnerMeterWithValuesInner struct {
	value *EventsDryRunResponseInnerMeterWithValuesInner
	isSet bool
}

func (v NullableEventsDryRunResponseInnerMeterWithValuesInner) Get() *EventsDryRunResponseInnerMeterWithValuesInner {
	return v.value
}

func (v *NullableEventsDryRunResponseInnerMeterWithValuesInner) Set(val *EventsDryRunResponseInnerMeterWithValuesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsDryRunResponseInnerMeterWithValuesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsDryRunResponseInnerMeterWithValuesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsDryRunResponseInnerMeterWithValuesInner(val *EventsDryRunResponseInnerMeterWithValuesInner) *NullableEventsDryRunResponseInnerMeterWithValuesInner {
	return &NullableEventsDryRunResponseInnerMeterWithValuesInner{value: val, isSet: true}
}

func (v NullableEventsDryRunResponseInnerMeterWithValuesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsDryRunResponseInnerMeterWithValuesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


