/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventsDryRunRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventsDryRunRequest{}

// EventsDryRunRequest struct for EventsDryRunRequest
type EventsDryRunRequest struct {
	Events []EventsDryRunRequestEventsInner `json:"events"`
}

type _EventsDryRunRequest EventsDryRunRequest

// NewEventsDryRunRequest instantiates a new EventsDryRunRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsDryRunRequest(events []EventsDryRunRequestEventsInner) *EventsDryRunRequest {
	this := EventsDryRunRequest{}
	this.Events = events
	return &this
}

// NewEventsDryRunRequestWithDefaults instantiates a new EventsDryRunRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsDryRunRequestWithDefaults() *EventsDryRunRequest {
	this := EventsDryRunRequest{}
	return &this
}

// GetEvents returns the Events field value
func (o *EventsDryRunRequest) GetEvents() []EventsDryRunRequestEventsInner {
	if o == nil {
		var ret []EventsDryRunRequestEventsInner
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *EventsDryRunRequest) GetEventsOk() ([]EventsDryRunRequestEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *EventsDryRunRequest) SetEvents(v []EventsDryRunRequestEventsInner) {
	o.Events = v
}

func (o EventsDryRunRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventsDryRunRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *EventsDryRunRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventsDryRunRequest := _EventsDryRunRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventsDryRunRequest)

	if err != nil {
		return err
	}

	*o = EventsDryRunRequest(varEventsDryRunRequest)

	return err
}

type NullableEventsDryRunRequest struct {
	value *EventsDryRunRequest
	isSet bool
}

func (v NullableEventsDryRunRequest) Get() *EventsDryRunRequest {
	return v.value
}

func (v *NullableEventsDryRunRequest) Set(val *EventsDryRunRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsDryRunRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsDryRunRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsDryRunRequest(val *EventsDryRunRequest) *NullableEventsDryRunRequest {
	return &NullableEventsDryRunRequest{value: val, isSet: true}
}

func (v NullableEventsDryRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsDryRunRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


