/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryEventsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryEventsResponse{}

// QueryEventsResponse struct for QueryEventsResponse
type QueryEventsResponse struct {
	// An array of events matching the query criteria
	Events []QueryEventsResponseEventsInner `json:"events"`
}

type _QueryEventsResponse QueryEventsResponse

// NewQueryEventsResponse instantiates a new QueryEventsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryEventsResponse(events []QueryEventsResponseEventsInner) *QueryEventsResponse {
	this := QueryEventsResponse{}
	this.Events = events
	return &this
}

// NewQueryEventsResponseWithDefaults instantiates a new QueryEventsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryEventsResponseWithDefaults() *QueryEventsResponse {
	this := QueryEventsResponse{}
	return &this
}

// GetEvents returns the Events field value
func (o *QueryEventsResponse) GetEvents() []QueryEventsResponseEventsInner {
	if o == nil {
		var ret []QueryEventsResponseEventsInner
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *QueryEventsResponse) GetEventsOk() ([]QueryEventsResponseEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *QueryEventsResponse) SetEvents(v []QueryEventsResponseEventsInner) {
	o.Events = v
}

func (o QueryEventsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryEventsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *QueryEventsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryEventsResponse := _QueryEventsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryEventsResponse)

	if err != nil {
		return err
	}

	*o = QueryEventsResponse(varQueryEventsResponse)

	return err
}

type NullableQueryEventsResponse struct {
	value *QueryEventsResponse
	isSet bool
}

func (v NullableQueryEventsResponse) Get() *QueryEventsResponse {
	return v.value
}

func (v *NullableQueryEventsResponse) Set(val *QueryEventsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryEventsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryEventsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryEventsResponse(val *QueryEventsResponse) *NullableQueryEventsResponse {
	return &NullableQueryEventsResponse{value: val, isSet: true}
}

func (v NullableQueryEventsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryEventsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


