/*
Vayu API

The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com

API version: 1.0.0
Contact: dev@withvayu.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ListMetersResponseMetersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMetersResponseMetersInner{}

// ListMetersResponseMetersInner struct for ListMetersResponseMetersInner
type ListMetersResponseMetersInner struct {
	// The name of the meter
	Name string `json:"name"`
	// The name of the event that the meter is tracking.
	EventName string `json:"eventName"`
	AggregationMethod AggregationMethod `json:"aggregationMethod"`
	Filter *Filter `json:"filter,omitempty"`
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _ListMetersResponseMetersInner ListMetersResponseMetersInner

// NewListMetersResponseMetersInner instantiates a new ListMetersResponseMetersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMetersResponseMetersInner(name string, eventName string, aggregationMethod AggregationMethod, id string, createdAt time.Time, updatedAt time.Time) *ListMetersResponseMetersInner {
	this := ListMetersResponseMetersInner{}
	this.Name = name
	this.EventName = eventName
	this.AggregationMethod = aggregationMethod
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewListMetersResponseMetersInnerWithDefaults instantiates a new ListMetersResponseMetersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMetersResponseMetersInnerWithDefaults() *ListMetersResponseMetersInner {
	this := ListMetersResponseMetersInner{}
	return &this
}

// GetName returns the Name field value
func (o *ListMetersResponseMetersInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListMetersResponseMetersInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListMetersResponseMetersInner) SetName(v string) {
	o.Name = v
}

// GetEventName returns the EventName field value
func (o *ListMetersResponseMetersInner) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *ListMetersResponseMetersInner) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *ListMetersResponseMetersInner) SetEventName(v string) {
	o.EventName = v
}

// GetAggregationMethod returns the AggregationMethod field value
func (o *ListMetersResponseMetersInner) GetAggregationMethod() AggregationMethod {
	if o == nil {
		var ret AggregationMethod
		return ret
	}

	return o.AggregationMethod
}

// GetAggregationMethodOk returns a tuple with the AggregationMethod field value
// and a boolean to check if the value has been set.
func (o *ListMetersResponseMetersInner) GetAggregationMethodOk() (*AggregationMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AggregationMethod, true
}

// SetAggregationMethod sets field value
func (o *ListMetersResponseMetersInner) SetAggregationMethod(v AggregationMethod) {
	o.AggregationMethod = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *ListMetersResponseMetersInner) GetFilter() Filter {
	if o == nil || IsNil(o.Filter) {
		var ret Filter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMetersResponseMetersInner) GetFilterOk() (*Filter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *ListMetersResponseMetersInner) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given Filter and assigns it to the Filter field.
func (o *ListMetersResponseMetersInner) SetFilter(v Filter) {
	o.Filter = &v
}

// GetId returns the Id field value
func (o *ListMetersResponseMetersInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListMetersResponseMetersInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListMetersResponseMetersInner) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListMetersResponseMetersInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListMetersResponseMetersInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListMetersResponseMetersInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ListMetersResponseMetersInner) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ListMetersResponseMetersInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ListMetersResponseMetersInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ListMetersResponseMetersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMetersResponseMetersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["eventName"] = o.EventName
	toSerialize["aggregationMethod"] = o.AggregationMethod
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListMetersResponseMetersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"eventName",
		"aggregationMethod",
		"id",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMetersResponseMetersInner := _ListMetersResponseMetersInner{}

	err = json.Unmarshal(data, &varListMetersResponseMetersInner)

	if err != nil {
		return err
	}

	*o = ListMetersResponseMetersInner(varListMetersResponseMetersInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "eventName")
		delete(additionalProperties, "aggregationMethod")
		delete(additionalProperties, "filter")
		delete(additionalProperties, "id")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListMetersResponseMetersInner struct {
	value *ListMetersResponseMetersInner
	isSet bool
}

func (v NullableListMetersResponseMetersInner) Get() *ListMetersResponseMetersInner {
	return v.value
}

func (v *NullableListMetersResponseMetersInner) Set(val *ListMetersResponseMetersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListMetersResponseMetersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListMetersResponseMetersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMetersResponseMetersInner(val *ListMetersResponseMetersInner) *NullableListMetersResponseMetersInner {
	return &NullableListMetersResponseMetersInner{value: val, isSet: true}
}

func (v NullableListMetersResponseMetersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMetersResponseMetersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


