name: Add Go Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The Go version to add"
        required: true

jobs:
  add_go_version:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies for gvm
        run: |
          sudo apt-get update
          sudo apt-get install -y bsdmainutils curl git mercurial make binutils bison gcc build-essential

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Validate and Add Go Version
        run: |
          bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
          chmod +x ./version_support/add_supported_version.sh
          ./version_support/add_supported_version.sh ${{ github.event.inputs.version }}

      - name: Commit changes
        run: |
          git add ./version_support/supported_versions.txt
          git commit -m "Add Go version ${{ github.event.inputs.version }}"
          exit 1

      - name: Push changes
        run: |
          git push origin main
