name: Go Build Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22.5', '1.22.3']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Update go.mod for Go ${{ matrix.go-version }}
      run: |
        go mod edit -go=${{ matrix.go-version }}
        go mod tidy

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build ./...

    - name: Run Tests
      run: go test ./...

    - name: Verify Build
      run: |
        if go build ./...; then
          echo "Build successful"
        else
          echo "Build failed"
          exit 1
        fi
