name: Version and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bumping_version_and_releasing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Read Go versions
        id: get_versions
        run: |
          VERSIONS=$(grep -v '^[[:space:]]*$' ./version_support/supported_versions.txt | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr '\n' ' ')
          LATEST_VERSION=$(echo "$VERSIONS" | awk '{print $1}')
          echo "SUPPORTED_VERSIONS=$VERSIONS" >> $GITHUB_ENV
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Get the current version
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Increment version
        run: |
          echo "Current version: $VERSION"
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch+1))
          new_version="$major.$minor.$patch"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Update version in VERSION file
        run: echo ${{ env.new_version }} > VERSION

      - name: Commit version bump
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version to ${{ env.new_version }}"
          git push origin main

      - name: Releasing GO versions tags
        run: |
          for version in ${{ env.SUPPORTED_VERSIONS }}; do
            echo "Releasing GO version $version"
            go mod edit -go=$version
            go mod tidy
            git add go.mod
            if [ -f go.sum ]; then
              git add go.sum
            fi
            git commit -m "Releasing for GO version $version" --allow-empty || echo "Nothing to commit"
            git tag "v${{ env.new_version }}-go$version"
            git push origin "v${{ env.new_version }}-go$version"
          done

      - name: Generate release body
        run: |
          echo "Release version ${{ env.new_version }}" > release_body.txt
          echo "" >> release_body.txt
          echo "### Supported Go Versions:" >> release_body.txt
          echo "- [latest](https://github.com/weft-finance/vayu-go/releases/tag/latest)" >> release_body.txt
          for version in ${{ env.SUPPORTED_VERSIONS }}; do
            echo "- [v${{ env.new_version }}-go$version](https://github.com/weft-finance/vayu-go/releases/tag/v${{ env.new_version }}-go$version)" >> release_body.txt
          done

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.new_version }}"
          release_name: "v${{ env.new_version }}"
          body_path: ./release_body.txt
          draft: false
          prerelease: false
